version: '3.8'

services:
  task_app:
    restart: always
    build:
      context: .
    image: task_app:v1.0
    container_name: task_app
    ports:
      - 7540:7540
    environment:
      - LOG_LEVEL=info
      - TODO_HOST=localhost
      - TODO_PORT=7540
      - TODO_DBFILE=./scheduler.db
      - TODO_PASSWORD=secret_pass
    deploy:
      restart_policy:
        condition: on-failure